@startmindmap
+ 内存问题
++ 内存不够用
+++ 将程序分成4K一页，用到哪块加载那块
+++ LRU 
++++ 内存不够时，使用LRU算法计算哪块内存需要被淘汰
+++ swap 分区
++++ 内存不够用时，LRU淘汰算法将内存中不常用分页放入交换区--处于磁盘上
++ 进程间内存相互打扰
+++ 虚拟内存
++++ 进程工作在虚拟空间上，不是直接物理空间
++++ 寻址大小：32位：2^32byte/64位：2^64byte
++++ 操作系统进行地址映射
+++++ 逻辑地址->线性地址->物理地址
+++++ mmu 
@endmindmap